### ISSUE TITLE
New 'atomic' stuff fails for me on linux

### ISSUE THREAD

**Issue by Vagabond** [helium/libhelium#14]
If I compile with gcc 4.9.0:

```
In file included from /home/andrew/libhelium/helium.c:8:0:
/home/andrew/libhelium/helium.c: In function 'helium_open':
/home/andrew/libhelium/helium_stdatomic.h:250:39: error: request for member '__val' in something not a structure or union
  __atomic_compare_exchange_n(&(object)->__val, expected,  \
                                       ^
/home/andrew/libhelium/helium_stdatomic.h:362:2: note: in expansion of macro 'atomic_compare_exchange_strong_explicit'
  atomic_compare_exchange_strong_explicit(object, 0, 1, order, order)
  ^
/home/andrew/libhelium/helium_stdatomic.h:367:2: note: in expansion of macro 'atomic_flag_test_and_set_explicit'
  atomic_flag_test_and_set_explicit(object, memory_order_seq_cst)
  ^
/home/andrew/libhelium/helium.c:448:20: note: in expansion of macro 'atomic_flag_test_and_set'
   _Bool was_open = atomic_flag_test_and_set(&conn->is_open);
                    ^
/home/andrew/libhelium/helium.c:448:3: error: incompatible type for argument 1 of '__atomic_compare_exchange_n'
   _Bool was_open = atomic_flag_test_and_set(&conn->is_open);
   ^
In file included from /home/andrew/libhelium/helium.c:8:0:
/home/andrew/libhelium/helium.c: In function 'helium_close':
/home/andrew/libhelium/helium_stdatomic.h:271:28: error: request for member '__val' in something not a structure or union
  __atomic_store_n(&(object)->__val, desired, order)
                            ^
/home/andrew/libhelium/helium_stdatomic.h:360:2: note: in expansion of macro 'atomic_store_explicit'
  atomic_store_explicit(object, 0, order)
  ^
/home/andrew/libhelium/helium_stdatomic.h:365:2: note: in expansion of macro 'atomic_flag_clear_explicit'
  atomic_flag_clear_explicit(object, memory_order_seq_cst)
  ^
/home/andrew/libhelium/helium.c:557:3: note: in expansion of macro 'atomic_flag_clear'
   atomic_flag_clear(&conn->is_open);
   ^
/home/andrew/libhelium/helium.c:557:3: error: incompatible type for argument 1 of '__atomic_store_n'
CMakeFiles/helium.dir/build.make:77: recipe for target 'CMakeFiles/helium.dir/helium.c.o' failed
make[2]: *** [CMakeFiles/helium.dir/helium.c.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/helium.dir/all' failed
make[1]: *** [CMakeFiles/helium.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

If I compile with clang 3.5.0 both test programs segfault:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000407c1f in helium_open (conn=0x60a0a0, proxy_addr=0x0,
    callback=0x4023e0 <test_callback2>) at /home/andrew/libhelium/helium.c:448
448       _Bool was_open = atomic_flag_test_and_set(&conn->is_open);
(gdb) bt
#0  0x0000000000407c1f in helium_open (conn=0x60a0a0, proxy_addr=0x0,
    callback=0x4023e0 <test_callback2>) at /home/andrew/libhelium/helium.c:448
#1  0x00000000004024a3 in main (argc=1, argv=0x7fffffffe868)
    at /home/andrew/libhelium/multiloop_test.c:34
```
